import { Post } from './post.model';

export const POSTS: Post[] = [
   new Post("Saw this woman getting a better view of the eclipse", "Grumpntug",
       "", "https://i.redd.it/fe6gycp1z4hz.jpg", "funny", 1),
   new Post("Don’t look at the sun without your glasses!", "whoaaintitfun",
       "", "https://i.redd.it/j6uj7kd9r4hz.jpg", "funny", 2),
    new Post("View of the Eclipse from an airplane", "xdel", "", "http://i.imgur.com/p8mod70.jpg", "woahdude", 3),
    new Post("Our Commander In Chief, everyone", "roberthardy1", "", "https://i.imgur.com/8P9EGBt.jpg", "facepalm", 4),
    new Post("Ukraine has removed all 1,320 statues of Lenin", "tellman1257", "Ukraine has removed all 1,320 statues of the communist revolutionary Lenin following a government drive to rid the country of Soviet-era symbols. Monuments to the Bolshevik leader have been dismantled in every town, village and city controlled by the Kiev-based government that brought down pro-Russian president Viktor Yanukovych three years ago, according to officials. The anti-Soviet initiative, which also orders the renaming of streets and cities, was made law by President Petro Poroshenko in May 2015, according to The Times. Many places have been named after Ukranian heroes, however a Lenin Street in Zakarpattia, a western region, was renamed Lennon Street in a tribute to the Beatles. Volodymyr Viatrovych, director of the Institute of National Remembrance, confirmed that every Lenin statue had been removed along with 1,069 other Soviet monuments. Despite the policy, Communist relics still remain in the eastern parts of Ukraine controlled by Kremlin-backed forces.", "", "worldnews", 5),
    new Post("99.50$ Camera Lense? Fucking Worth It", "Stevenm50", "", "https://i.redd.it/qdnq79mml4hz.jpg", "natureisfuckinglit", 6),
    new Post("It's official, Android 8.0 is Oreo", "Ibleedcarrots", "", "https://storage.googleapis.com/gweb-uniblog-publish-prod/original_images/Android-Oreo-Transformation.gif", "muckingfagical", 7),
    new Post("Study tested whether video game players could operate UAVs as effectively as pilots. Gamers displayed less overconfidence when deciding to intervene/override the system.", "BocceBaller42", "Unmanned Aerial Systems (UAS) operations have outpaced current training regimes resulting in a shortage of qualified UAS pilots. Three potential UAS operator groups were explored for suitability (i.e. video game players [VGP]; private pilots; professional pilots) and examined to assess levels of accuracy, confidence and confidence-accuracy judgements (W-S C-A) during a simulated civilian cargo flight. Sixty participants made 21 decision tasks, which varied across three levels of danger/risk. Scales of Tolerance of Ambiguity, Decision Style and NEO-PIR were also completed. Professional pilots and VGPs exhibited the highest level of decision confidence, with VGPs maintaining a constant and positive W-S C-A relationship across decision danger/risk. As decision danger/risk increased, confidence, accuracy and W-S C-A decreased. Decision danger also had a role to play in the confidence expressed when choosing to intervene or rely on automation. Neuroticism was negatively related, and conscientiousness positively related, to confidence. Intolerance of ambiguity was negatively related to W-S C-A. All groups showed higher levels of decision confidence in decisions controlled by the UAS in comparison to decisions where the operator manually intervened. VGPs display less overconfidence in decision judgements. Findings support the idea that VGPs could be considered a resource in UAS operation.", "", "science", 8),
    new Post("Kids learn moral lessons more effectively from stories with humans than human-like animals", "TomG93", "Four to-six-year olds shared more with each other after listening to audiobooks with human characters rather than human-like animals, a new study has shown. Researchers from the Ontario Institute for Studies in Education at the University Toronto have published their findings in their paper Do storybooks with anthropomorphized animal characters promote prosocial behaviors in young children?. Dr Patricia Ganea, associate professor of early cognitive development at OISE, said: 'These findings add to a growing body of research showing that children find it easier to apply knowledge from stories that are realistic. 'Overall, children were more likely to act on the moral of the story when it featured a human character.' In the study, children listened to a story featuring either a human or human-like animal character who spoke and wore clothes. The books taught children about sharing with others, and the children's altruistic giving was determined by an assessment both before and after the reading. The team found that children shared more after listening to the book with humans. Dr Ganea said: 'Books that children can easily relate to increase their ability to apply the story's lesson to their daily lives. 'It is important for educators and parents to choose carefully when the goal is to teach real-world knowledge and social behaviours through storybooks.' The children had a chance to share ten stickers with another child before listening to the stories. Children shared more after reading the human book and less after reading the animal book.", "", "science", 9)
 ];
